### ISSUE TITLE
End the process and delete files

### ISSUE THREAD

**Issue by ttsite** [b1-team/superman#4]
Can you add an end process and forcibly delete the file where the process is located? Thank you!

**Comment by b1nhack** [comment]
Did u mean delete the file released by the program?

**Comment by ttsite** [comment]
> Did u mean delete the file released by the program?

Delete the file of the terminated process. Prevent it from being resurrected again

**Comment by b1nhack** [comment]
No, this is not a good idea, you can use the -r parameter for this purpose, and the -t parameter to set a smaller refresh time.

**Comment by b1nhack** [comment]
I will close this issue, and if you feel that the benefits outweigh the disadvantages, you can open another issue.
