### ISSUE TITLE
execute problem 

### ISSUE THREAD

**Issue by Jigsaw855** [b1-team/superman#6]
hi 
I execute your tools despite of  it kill defender process but defender is not off ,now what I must to do defender will be  off

**Comment by b1nhack** [comment]
You should find the exact defense process (which may be more than one), and then kill them both

**Comment by langyajiekou** [comment]
gmer abuse is easily to be detected.

**Comment by b1nhack** [comment]
> gmer abuse is easily to be detected.

You're right, but you can check out this repo: https://github.com/med0x2e/SigFlip
