### ISSUE TITLE
I have an error when compiling

### ISSUE THREAD

**Issue by marcosd2234** [b1-team/superman#9]
Hello, I'm somewhat new to this, but I wanted to try the project, but when I compiled I got an error, and it marked the executable as if I needed administrator permissions to run it.

![1](https://github.com/b1-team/superman/assets/149676151/9af44461-35e4-434b-b167-05a267a709cf)

**Comment by b1nhack** [comment]
BYOVD technology requires the use of the Windows API to load the driver, this operation requires administrator privileges.
There is one more error you may encounter: the latest Windows 10/11 systems blacklist the driver used by superman, it cannot be loaded properly, it is recommended to test with Windows Server 2019.
